name = "schemabio-backend"
main = "src/index.py"
compatibility_date = "2024-04-05"
compatibility_flags = ["python_workers"]

[[d1_databases]]
binding = "DB"
database_name = "schemabio-db"
database_id = "52b7fff9-aa81-48fa-a4c4-cbf4585fea75"

# 绑定环境变量 (本地开发占位符)
[vars]
# FIREBASE_CREDENTIALS = "secret"

[observability]
enabled = true