name = "schemabio-backend"
main = "src/index.py"
compatibility_date = "2024-04-05"
compatibility_flags = ["python_workers"]

# 绑定环境变量 (本地开发占位符)
[vars]
# FIREBASE_CREDENTIALS = "secret"

[observability]
enabled = true